apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hostpid
  name: hostpid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostpid
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hostpid
    spec:
      hostPID: true
      containers:
      - image: nginx
        name: nginx
